### ISSUE TITLE
Show/Hide code block

### ISSUE THREAD

**Issue by hakril** [fmichea/lpbm#1]
It would be a killer feature to have hideable code block in LPBM !

What do you think ?

**Comment by fmichea** [comment]
Hi,

Yes that would be a good feature. I think it is doable using the extension feature provided by the Markdown module. But first a syntax must be decided that does not conflict with standard Markdown.

The code highlighter uses :::lang to denote the language to highlight in, maybe we could use something similar and extend that class.

```
:::lpbm:colapser lines=5 default=colapsed label="Fooooo"
:::python
print 'Hello World!'
```

Or something like that. Ideas?

**Comment by fmichea** [comment]
Merged in master. Will be included in next release.
